/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package happypaws;

import javax.swing.JOptionPane;

/**
 *
 * @author tharu
 */
public class MedicalForm extends javax.swing.JFrame {

    /**
     * Creates new form MedicalForm
     */
    public MedicalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rec1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ani1 = new javax.swing.JTextField();
        dte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        syp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dig = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        trt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Diagnosis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 90, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Record ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setText("MEDICAL DATA FORM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 440, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Animal ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 70, 50));

        rec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec1ActionPerformed(evt);
            }
        });
        getContentPane().add(rec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 550, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 42, 50));

        ani1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ani1ActionPerformed(evt);
            }
        });
        getContentPane().add(ani1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 550, 50));

        dte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteActionPerformed(evt);
            }
        });
        getContentPane().add(dte, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 550, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Symptoms");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, 50));

        syp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sypActionPerformed(evt);
            }
        });
        getContentPane().add(syp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 550, 50));

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 190, 90));

        dig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digActionPerformed(evt);
            }
        });
        getContentPane().add(dig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 550, 50));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 180, 90));

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 180, 90));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Treatmen ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 100, 50));

        trt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trtActionPerformed(evt);
            }
        });
        getContentPane().add(trt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 550, 50));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 910, 70));

        setSize(new java.awt.Dimension(1934, 1117));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rec1ActionPerformed

    private void ani1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ani1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ani1ActionPerformed

    private void dteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dteActionPerformed

    private void sypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sypActionPerformed

    private void digActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          connect connect= new connect();
connect.dbsconnection();
 String id= rec1.getText();
 int intId = Integer.parseInt(id);
  connect.meddeleteData(intId);
  
  //POPUP
  JOptionPane.showConfirmDialog(this,"Do You Want To Delete data??");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connect connect=new connect();
 connect.dbsconnection();
  String id= rec1.getText();
  
  int b= Integer.parseInt(id);
  
  connect.medsearchData(b);
  
  //POPUP
  JOptionPane.showMessageDialog(this,"ID FOUND!!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            connect connect=new connect();
 connect.dbsconnection();
  String id=rec1.getText();
  String Ani = ani1.getText();
  String date= dte.getText();
  String sm= syp.getText();
 String diog= dig.getText();
 String Trt= trt.getText();
  
  int a = Integer.parseInt(id);
  int b = Integer.parseInt(Ani);
  int c = Integer.parseInt(date);
  
  
  connect.medData(a,b,c,sm,diog,Trt);
  
  //POPUP
  
JOptionPane.showMessageDialog(this,"INSERTED SUCCESSFULLY!!");
    }//GEN-LAST:event_jButton1ActionPerformed

   
  
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         //back to ui
        UserInterface ui= new UserInterface();
        ui.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void trtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ani1;
    private javax.swing.JTextField dig;
    private javax.swing.JTextField dte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField rec1;
    private javax.swing.JTextField syp;
    private javax.swing.JTextField trt;
    // End of variables declaration//GEN-END:variables
}
